### ISSUE TITLE
Failed to activate the ease-blink package

### ISSUE THREAD

**Issue by phyllisstein** [miraks/ease-blink#6] opened 2015-03-11 05:25 UTC
Hey there! I'm seeing the error below every time I open a new window in Atom. The package seems ultimately to load---I can see the cursor easing in and out---and creating new tabs is fine, but I get that little red error popup reliably on each new window. Thanks in advance for looking into it, and for a great package!

---

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.3
**Thrown From**: [ease-blink](https://github.com/miraks/ease-blink) package, v0.4.1

### Stack Trace

Failed to activate the ease-blink package

```
At undefined is not a function

TypeError: undefined is not a function
    at Object.module.exports.updateEditorViews (/Users/danielsh/.atom/packages/ease-blink/lib/ease-blink.coffee:31:76)
    at /Users/danielsh/.atom/packages/ease-blink/lib/ease-blink.coffee:21:24
    at Array.forEach (native)
    at Object.module.exports.changeBlinkPeriod (/Users/danielsh/.atom/packages/ease-blink/lib/ease-blink.coffee:19:53)
    at Config.module.exports.Config.observeKeyPath (/Applications/Atom.app/Contents/Resources/app/src/config.js:621:7)
    at Config.module.exports.Config.observe (/Applications/Atom.app/Contents/Resources/app/src/config.js:133:21)
    at Object.module.exports.setupConfigObserver (/Users/danielsh/.atom/packages/ease-blink/lib/ease-blink.coffee:16:26)
    at Object.module.exports.activate (/Users/danielsh/.atom/packages/ease-blink/lib/ease-blink.coffee:13:19)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:240:19)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:221:30
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ],
    "destroyEmptyPanes": false,
    "excludeVcsIgnoredPaths": false,
    "followSymlinks": true,
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "Thumbs.db",
      "node_modules",
      ".bundle",
      ".capistrano",
      "bin",
      "log",
      "tmp",
      "bower_components",
      ".keep"
    ],
    "projectHome": "/Users/danielsh/Repos",
    "disabledPackages": [
      "wrap-guide",
      "deprecation-cop",
      "keybinding-resolver",
      "autocomplete",
      "background-tips",
      "markdown-preview-pandoc"
    ]
  },
  "ease-blink": {}
}
```

### Installed Packages

```coffee
# User
Stylus, v0.6.0
atom-alignment, v0.11.0
atom-color-highlight, v3.0.8
atomatigit, v1.2.3
autoclose-html, v0.15.0
build, v0.26.0
caniuse, v0.5.3
circle-ci, v0.6.2
color-picker, v1.4.4
docblockr, v0.6.3
ease-blink, v0.4.1
figlet, v0.3.1
file-icons, v1.5.1
file-types, v0.3.0
hipster-ipsum, v0.1.0
http-status-codes, v1.0.3
iTunes, v0.2.0
keybinding-cheatsheet, v0.0.8
language-latex, v0.4.1
language-rspec, v0.3.0
latex, v0.19.1
less-than-slash, v0.4.1
linter, v0.12.0
linter-coffeelint, v0.1.7
linter-flake8, v1.3.0
linter-js-yaml, v1.0.0
linter-pyflakes, v0.0.4
linter-rubocop, v0.2.2
pain-split, v1.3.1
pdf-view, v0.17.0
project-manager, v1.15.5
project-palette-finder, v2.4.16
remote-atom, v1.2.0
remote-edit, v1.7.2
resize-indent, v0.2.1
slim-language, v2.0.0
tasks, v1.3.0
travis-ci-status, v0.13.0
tree-ignore, v0.2.5
web-browser, v1.4.2
wordcount, v2.1.0

# Dev
No dev packages
```

**Comment by miraks** [comment] 2015-03-11 08:33
Hey. Thank for reporting this. Should be fixed now.

**Comment by phyllisstein** [comment] 2015-03-11 08:48
Indeed it is! Thanks so much for the speedy repair.

**Comment by Gert-dev** [comment] 2016-04-28 18:26
Hello, sorry to trouble you again, but this issue seems to be back (possibly in another form), the backtrace:

```
At Cannot read property 'style' of undefined

TypeError: Cannot read property 'style' of undefined
    at Object.module.exports.updateCssRule (/home/me/.atom/packages/ease-blink/lib/ease-blink.coffee:44:18)
    at /home/me/.atom/packages/ease-blink/lib/ease-blink.coffee:21:7
    at Array.forEach (native)
    at Object.module.exports.changeBlinkPeriod (/home/me/.atom/packages/ease-blink/lib/ease-blink.coffee:20:44)
    at Config.module.exports.Config.observeKeyPath (/usr/share/atom/resources/app.asar/src/config.js:612:7)
    at Config.module.exports.Config.observe (/usr/share/atom/resources/app.asar/src/config.js:141:21)
    at Object.module.exports.setupConfigObserver (/home/me/.atom/packages/ease-blink/lib/ease-blink.coffee:17:17)
    at Object.module.exports.activate (/home/me/.atom/packages/ease-blink/lib/ease-blink.coffee:14:6)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:183:20)
    at /usr/share/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:538:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:497:46)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:754:28
```

**Comment by miraks** [comment] 2016-04-28 20:21
Hello, I just published new version of the package. I couldn't reproduce your issue on most recent versions of the atom and atom-beta, but I made some code refactoring, so it can be fixed now. Can you update the package and check if issue is resolved?

**Comment by Gert-dev** [comment] 2016-04-29 16:14
I can confirm that fixes it, thanks!

**Comment by miraks** [comment] 2016-04-29 16:15
Great!

**Closed by miraks** 2016-04-29 16:15 UTC
